# Make binary generated by local compilation go into a build folder so it's easier to add to .gitignore
switch("backend", "cpp")
switch("path", "..")
when not defined(testing):
  switch("outdir", "bin")

