# Make binary generated by local compilation go into a build folder so it's easier to add to .gitignore
switch("outdir", "build")
when defined(debug):
  switch("debugger", "native")
  switch("define", "useMalloc")
