on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v4
        with:
          version: 1.9.3
      - run: git submodule update --recursive --init
      - run: nimble install -y
      - run: nimble test
      # TODO : make examples works
      # - run: nimble runexample

